version: '3.7'
services:
  server:
    container_name: backend
    image: server:dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3002:3000
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - server:/server/node_modules
      - ${PWD}:server
    environment:
    - CHOKIDAR_USEPOLLING=true
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  server: